### ISSUE TITLE
Have you considered contributing the patches here back to miniserde under a feature flag?

### ISSUE THREAD

**Issue by dralley** [cloudhead/microserde#1]
This isn't meant to be a criticism, but since this fork only changes a couple of lines compared to miniserde, I'm wondering if contributing those changes directly was considered?

Obviously miniserde probably wants to keep the fast float parsing and such, but maybe they'd consider a feature flag that allows disabling it?

**Comment by dralley** [comment]
Never mind https://github.com/dtolnay/miniserde/issues/19

**Comment by cloudhead** [comment]
Yeah, unfortunate but I tried!
